### ISSUE TITLE
Add visual guide

### ISSUE THREAD

**Issue by jonasmuriboe** [hbirchtree/it2901-project#14]
Create a visualization showing how the different actions in game maps to the different buttons on the controller

**Comment by Camorte** [comment]
https://www.dropbox.com/s/705e7hyb9aeqw7w/Vive%20visual%20guide-02.png?dl=0 Image guide

**Comment by Camorte** [comment]
https://www.dropbox.com/s/mfnej6jcnhz250b/Vive%20visual%20guide%20Old-02.png?dl=0
